version: '3.8'

services:
  microservice1:
    build: ./microservice1
    container_name: microservice1
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/microservice1_db
    depends_on:
      - postgres
    networks:
      - app-network

  microservice2:
    build: ./microservice2
    container_name: microservice2
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservice1_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build: ./react_frontend_microservice
    container_name: react_frontend
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
