version: '3.8'

services:
  backend:
    build: ./nodejs_backend_microservice
    container_name: nodejs_backend_microservice
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/backend_db
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    build: ./postgres_microservice
    container_name: postgres_microservice
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build: ./react_frontend_microservice
    container_name: react_frontend_microservice
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
